export const ActionTypes = {
  SET_USERS: "SET_USERS",
  SELECTED_USER: "SELECTED_USER",
  SET_POSTS: "SET_POSTS",
  SELECTED_POSTS: "SELECTED_POSTS",
  SET_COMMENTS: "SET_COMMENTS",
  SELECTED_COMMENT: "SELECTED_COMMENT",
};
